const { contextBridge, ipcRenderer } = require('electron')

contextBridge.exposeInMainWorld('widget', {
  getCfg: () => ipcRenderer.invoke('get-cfg'),
  setCfg: (patch) => ipcRenderer.send('set-cfg', patch),
  onCfg: (cb) => ipcRenderer.on('cfg', (_e, c) => cb(c)),
  getSize: () => ipcRenderer.invoke('get-size'),
  setSize: (s) => ipcRenderer.send('set-size', s),
  react: (name) => ipcRenderer.send('react', name),
  onReact: (cb) => ipcRenderer.on('react', (_e, n) => cb(n)),
  onCursor: (cb) => ipcRenderer.on('cursor', (_e, p) => cb(p)),
  onDragging: (cb) => ipcRenderer.on('dragging', () => cb()),
  resizeStart: () => ipcRenderer.send('resize-start'),
  resizeEnd: () => ipcRenderer.send('resize-end'),
  moveStart: () => ipcRenderer.send('move-start'),
  moveEnd: () => ipcRenderer.send('move-end'),
  toggleSettings: () => ipcRenderer.send('toggle-settings'),
  bridgeConnect: () => ipcRenderer.send('bridge-connect'),
  bridgeDisconnect: () => ipcRenderer.send('bridge-disconnect'),
  getBridgeStatus: () => ipcRenderer.invoke('get-bridge-status'),
  onBridgeStatus: (cb) => ipcRenderer.on('bridge-status', (_e, s) => cb(s)),
  getHello: () => ipcRenderer.invoke('get-hello'),
  onHello: (cb) => ipcRenderer.on('hello', (_e, h) => cb(h)),
  refreshBots: () => ipcRenderer.send('refresh-bots'),
  onChatDelta: (cb) => ipcRenderer.on('chat-delta', (_e, d) => cb(d)),
  onChatError: (cb) => ipcRenderer.on('chat-error', (_e, d) => cb(d)),
  onChatHistory: (cb) => ipcRenderer.on('chat-history', (_e, h) => cb(h)),
  onNotify: (cb) => ipcRenderer.on('notify', (_e, n) => cb(n)),
  onNotifyClear: (cb) => ipcRenderer.on('notify-clear', () => cb()),
  onSpeak: (cb) => ipcRenderer.on('speak', (_e, s) => cb(s)),
  voiceHush: () => ipcRenderer.send('voice-hush'),
  getAutostart: () => ipcRenderer.invoke('get-autostart'),
  setAutostart: (on) => ipcRenderer.send('set-autostart', on),
  resetThread: () => ipcRenderer.send('reset-thread'),
  ogFetch: (url) => ipcRenderer.invoke('og-fetch', url),
  toggleChat: () => ipcRenderer.send('toggle-chat'),
  faceMenu: () => ipcRenderer.send('face-menu'),
  closeChat: () => ipcRenderer.send('close-chat'),
  chatSize: (h) => ipcRenderer.send('chat-size', h),
  chatSend: (text) => ipcRenderer.send('chat-send', text),
  onChatReply: (cb) => ipcRenderer.on('chat-reply', (_e, r) => cb(r)),
  onChatState: (cb) => ipcRenderer.on('chat-state', (_e, s) => cb(s)),
  onChatFocus: (cb) => ipcRenderer.on('chat-focus', () => cb()),
  quit: () => ipcRenderer.send('quit'),
})
